### ISSUE TITLE
Planning to move this to standalone?

### ISSUE THREAD

**Issue by pilot538** [rafaga/webb#1]
o7, I found this library while exploring [rfesi](https://github.com/celeo/rfesi) and saw you were using that library, and then stopped. 

Is your intention to make this a standalone Rust library for the ESI? Or should I use and contribute to `rfesi` for my new project?

Thanks!

**Comment by rafaga** [comment]
Hello thank for contacting me.  Being honest its hard to answer your question, because I have never though in webb as standalone library.

And I won't discard such idea. The library it would works as standalone easily at this stage of development.

webb its still on active development, for now I'm focusing on telescope and resolving some issues that I have found there,and I would continue adding more features to webb when I resolve those problems.

I'm open to any contributions and would like to know about your ideas.

But let me clarify that webb and rfesi are two different types of libraries

Rfesi provides a easy way to use the ESI api on rust 

And webb its a library that implement rfesi and make concrete things with esi like authencating and managing user, in the future will provide an easy way to manage its location and get intel from multiple sources

**Comment by pilot538** [comment]
Thanks for replying! 

Understood, I think for now I will look into using rfesi and adding more support for endpoints there. 

Best of luck with telescope and webb!
